### ISSUE TITLE
999+ warnings when building + asking for Swift 5 conversion

### ISSUE THREAD

**Issue by Verminator12** [AnyChart/AnyChart-iOS#5]
Hi,

I tried the Pie chart example in my app and the compiler found 4228 warnings, all of them about "Comparing non-optional value of type 'X' to 'nil' always returns true".

<img width="664" alt="Screenshot 2020-04-19 at 14 12 06" src="https://user-images.githubusercontent.com/43635658/79695956-c190c280-8247-11ea-90fe-44352b9c226a.png">

I also have a warning saying that I can convert AnyChartiOS.framework to Swift 5 but the conversion fails.

I am using the last version of Xcode and building my app for iOS 13.0 and above.

**Comment by Shestac92** [comment]
@Verminator12 
These warnings don't affect the functionality, at the moment you can ignore them for sure.
Swift 5 support is not scheduled yet, but we will take it into account for future updates.

**Comment by Verminator12** [comment]
@Shestac92 
Ok, I see. Thank you for the quick answer ;)
